### ISSUE TITLE
Compatibility with electron

### ISSUE THREAD

**Issue by rahulgopinathan** [bkobkobko/SparkTimeAlarms#10]
Is the library supports Electrons or it is only for the core?

**Comment by bkobkobko** [comment]
Hi @rahulgopinathan 

This is a port of an Arduino library.  It has been tested on Core and Photon but I have not personally tested it on an Electron.  There is an issue with macros that this code uses so after the `#include` for this library, you should do `#undef now()`

**Comment by rahulgopinathan** [comment]
Hey @bkobkobko,
Thanks for the info! The library worked great on the photon. I will test this on Electron using `#undef now()` and let you know.

**Comment by rahulgopinathan** [comment]
Working great now. Added `#undef now()` and `Alarm.delay(1000)` and Electron is working as expected.Thanks for the help!
