### ISSUE TITLE
migrating time alarms from arduino yield compilation erro

### ISSUE THREAD

**Issue by Lcstyle** [bkobkobko/SparkTimeAlarms#5]
Veryfing code using this library in Particle Build fails with this error:     TimeAlarms/TimeAlarms.h:14:20: error: expected     before  .  token #define now    Time.now   time_zone_cache  ^    

In file included from flashee-eeprom/flashee-eeprom.h:249:0,
                 from refill.cpp:2:
flashee-eeprom/flashee-eeprom-impl.h:1299:0: warning: "sFLASH_PAGECOUNT" redefined [enabled by default]
         #define sFLASH_PAGECOUNT (512)
 ^
In file included from ../platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc/hw_config.h:34:0,
                 from ../hal/src/core/platform_headers.h:18,
                 from ./inc/application.h:32,
                 from OneWire/OneWire.h:5,
                 from refill.cpp:1:
../platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc/sst25vf_spi.h:34:0: note: this is the location of the previous definition
 #define sFLASH_PAGECOUNT                                512             /\* 2MByte storage */
 ^
In file included from refill.cpp:3:0:

This looks like an error in TimeAlarms library. Would you like to create an issue on GitHub to let the author know?

TimeAlarms/TimeAlarms.h:14:20: error: expected ')' before '.' token
 #define now() (Time.now()+time_zone_cache)
                    ^

SparkTime/SparkTime.h:48:12: note: in expansion of macro 'now'
   uint32_t now();
            ^

This looks like an error in SparkTime library. Would you like to create an issue on GitHub to let the author know?

SparkTime/SparkTime.h:56:30: error: expected ')' before 'tnow'
   uint8_t dayOfWeek(uint32_t tnow);
                              ^

TimeAlarms/TimeAlarms.h:30:32: note: in definition of macro 'dayOfWeek'
 #define dayOfWeek(_time_)  ((( _time_ / SECS_PER_DAY + 4)  % DAYS_PER_WEEK)+1) // 1 = Sunday
                                ^
SparkTime/SparkTime.h:56:30: error: expected ')' before 'tnow'
   uint8_t dayOfWeek(uint32_t tnow);
                              ^
TimeAlarms/TimeAlarms.h:30:32: note: in definition of macro 'dayOfWeek'
 #define dayOfWeek(_time_)  ((( _time_ / SECS_PER_DAY + 4)  % DAYS_PER_WEEK)+1) // 1 = Sunday
                                ^
SparkTime/SparkTime.h:56:30: error: expected ')' before 'tnow'
   uint8_t dayOfWeek(uint32_t tnow);
                              ^
TimeAlarms/TimeAlarms.h:30:32: note: in definition of macro 'dayOfWeek'
 #define dayOfWeek(_time_)  ((( _time_ / SECS_PER_DAY + 4)  % DAYS_PER_WEEK)+1) // 1 = Sunday
                                ^
refill.cpp:100:1: error: 'tmElements_t' does not name a type
 long upTime = -1; // time the button was released
 ^
make[2]: **\* [../build/target/user/platform-0-lrefill.o] Error 1
make[1]: **\* [user] Error 2
make: **\* [main] Error 2

**Comment by bkobkobko** [comment]
Hi @Lcstyle 

Can you add 

`#undef now()`

after the include statement for the library.

There are many errors in the output above and most of them are not related to TimeAlarms ported to Particle.  Can you give me a simple test case?

It could be that you are trying to use TimeAlarms with my other library SparkTime for the NTP but these are not compatible.  TimeAlarms was ported after Particle added an built-in time function and so it works with that.  My SparkTime library was created before the Particle team added any time handling functions--it is still useful if you want more accurate time (true NTP) but it does not work with TimeAlarms.

**Comment by Lcstyle** [comment]
As I mentioned in the other ticket I'm in the process of porting code over to the photon and received a number of compilation errors.  Feel free to shelve this ticket if it isn't immediately obvious what the problem is, as it may be on my end. Thanks again.

**Comment by Lcstyle** [comment]
OK. I resolved it by undefining both now and day of week.
I am not sure but this might be a conflict with the Spark TimeAlarms?
The following sequence in the exact order worked:

Edit: I'm doing some additional work to use the default time functions in particle photon.

In TimeAlarms.cpp:

```
#include <SparkTime.h>
#undef now()
```

It was exactly this as you mentioned:

> It could be that you are trying to use TimeAlarms with my other library SparkTime for the NTP but these are not compatible. TimeAlarms was ported after Particle added an built-in time function and so it works with that. My SparkTime library was created before the Particle team added any time handling functions--it is still useful if you want more accurate time (true NTP) but it does not work with TimeAlarms.

I don't need time that accurate, instead I am doing Particle.syncTime every 24 hours:

```

/// in defines:

#define ONE_DAY_MILLIS (24 * 60 * 60 * 1000)
unsigned long lastSync = millis();

///inside loop():

  if (millis() - lastSync > ONE_DAY_MILLIS)
  {   // Request time synchronization from the Particle Cloud
    Particle.syncTime();
    lastSync = millis();
  }
```
