### ISSUE TITLE
'M' was not declared in this scope

### ISSUE THREAD

**Issue by GroovyGrovesy** [bkobkobko/SparkTimeAlarms#7]
Veryfing code using this library in Particle Build fails with this error:

```
TimeAlarms/TimeAlarms.h:43:27: error: 'M' was not declared in this scope
 #define minutesToTime_t ((M)) ( (M) * SECS_PER_MIN)  
                           ^
```

**Comment by bkobkobko** [comment]
Hi @GroovyGrovesy 

I just compiled the example app in Particle Build web IDE for a Photon and do not get this error.

Do you have other include files that could be cause this?

Can you provide a small example program to demonstrate the bug?

**Comment by bkobkobko** [comment]
This is very old and not reproducible.
